mydata <- read.csv("/media/sf_AIDD/DEI/Results/all_count_matrixEdit.csv")
wss <- (nrow(mydata[5:8])-1)*sum(apply(mydata[5:8],2,var))
for (i in 2:15) wss[i] <- sum(kmeans(mydata[5:8], centers=i)$withinss)
tiff("/media/sf_AIDD/DEI/Results/clustering.tiff", units="in", width=10, height=10, res=600)
plot(1:15, wss, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
dev.off() 
fit <- kmeans(mydata[5:8], 3)
aggregate(mydata[5:8],by=list(fit$cluster),FUN=mean)
mydata <- data.frame(mydata, fit$cluster)
d <- dist(mydata[5:8], method = "euclidean")
fit <- hclust(d, method="ward.D")
tiff("/media/sf_AIDD/DEI/Results/clusteringH.tiff", units="in", width=30, height=10, res=600)
plot(fit)
dev.off()
groups <- cutree(fit, k=5)
rect.hclust(fit, k=5, border="red")
fit <- pvclust(mydata[5:8], method.hclust="ward.D", method.dist="euclidean")
tiff("/media/sf_AIDD/DEI/Results/clusteringHbootstrap.tiff", units="in", width=10, height=10, res=600)
plot(fit)
pvrect(fit, alpha=.95)
dev.off()


mydata <- read.csv("/media/sf_AIDD/DEI/Results/excitome_count_matrix.csv")
mydata.pca <- prcomp(mydata[2:63])
summary(mydata.pca)
str(mydata.pca)
library(devtools)
library(ggbiplot)
ggbiplot(mydata.pca)

