#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
file_in <- paste0(args[1]) #"$dirres"/RF_count_matrix.csv
image1 <- paste0(args[2]) 
image2 <- paste0(args[3]) 
image3 <- paste0(args[4]) 
image4 <- paste0(args[5]) 
image5 <- paste0(args[6]) 
image6 <- paste0(args[7]) 
image7 <- paste0(args[8]) 
image8 <- paste0(args[9]) 
image9 <- paste0(args[10])
file_out <- paste0(args[11])
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("RColorBrewer")) 
suppressPackageStartupMessages(library("plot3D")) 
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("parallel"))
suppressPackageStartupMessages(library("randomForestSRC"))
suppressPackageStartupMessages(library("ggRandomForests"))
suppressPackageStartupMessages(library("GenomicAlignments"))
theme_set(theme_bw())
event.marks <- c(1, 4)
event.labels <- c(FALSE, TRUE)
data1=read.csv(file_in)
#dta <- melt(data1, id.vars=c("region","GRIA2_1edited"))
#ggplot(dta, aes(x=region, y=value, color=GRIA2_1edited)) + geom_point(alpha=.4) + geom_rug(data=dta %>% filter(is.na(value))) + scale_color_brewer(palette="Set2") + facet_wrap(~variable, scales="free_y", ncol=3)
rfsrc_regions <- rfsrc(samp_name~.,data=data1,nodesize=6,na.action = "na.impute",importance=TRUE)
rfsrc_regions
out <- capture.output(rfsrc_regions)
write.csv(out, file_out, row.names=FALSE, quote=FALSE)
cat("file_nameRF", out, file=file_out, sep="n", append=TRUE)

tiff(image1, units="in", width=10, height=10, res=600)
plot(gg_rfsrc(rfsrc_regions), alpha=.33)
dev.off()
tiff(image2, units="in", width=10, height=10, res=600)
plot(gg_vimp(rfsrc_regions))
dev.off()
varsel_regions <- var.select(rfsrc_regions)
data(varsel_regions)
gg_md <- gg_minimal_depth(varsel_regions)
tiff(image3, units="in", width=10, height=10, res=600)
plot(gg_md)
dev.off()
tiff(image4, units="in", width=10, height=10, res=600)
plot(gg_minimal_vimp(varsel_regions))
dev.off()
gg_v <- gg_variable(rfsrc_regions)
xvar <- gg_md$topvars
tiff(image5, units="in", width=10, height=10, res=600)
plot(gg_v, xvar=xvar, panel=TRUE, se=.95, span=1.2, alpha=.4)
dev.off()
tiff(image6, units="in", width=10, height=10, res=600)
plot(gg_v, xvar="GRIA2_1edited", points=FALSE, se=FALSE, notch=TRUE, alpha=.4)
dev.off()
tiff(image7, units="in", width=10, height=10, res=600)
partial_regions <- plot.variable(rfsrc_regions,xvar=gg_md$topvars,partial=TRUE, sorted=FALSE,show.plots = FALSE)
dev.off()
interaction_regions <- find.interaction(rfsrc_regions)
interaction_regions
tiff(image8, units="in", width=10, height=10, res=600)
plot(gg_interaction(interaction_regions), xvar=gg_md$topvars, panel=TRUE)
dev.off()
tiff(image9, units="in", width=30, height=10, res=600)
model <- randomForest(region~.,data=data1,importance=TRUE,ntree=1000,mtry=6,do.trace=100)
reprtree:::plot.getTree(model)
dev.off()
rfsrc_regions
out <- capture.output(rfsrc_regions)
write.csv(out, file_out, row.names=FALSE, quote=FALSE)
cat("file_nameRF", out, file=file_out, sep="n", append=TRUE)

