library(ggplot2)
tiff("/media/sf_AIDD/Results/DESeq2/transcript/differential_expression/ADARB2.tiff", units="in", width=10, height=10, res=900)
data1 <- read.csv("/media/sf_AIDD/Results/DESeq2/transcript/differential_expression/ADARB2.csv")
data1$index <- factor(data1$index, levels=unique(data1$index))
ggplot(data=data1, aes(x=index, y=counts, fill=condition)) + geom_bar(stat="identity", position=position_dodge(), colour="black") + scale_fill_manual(values=c("#FF6666", "#FFFF99", "#66FF66", "#6633FF", "#CC66FF")) + labs(x = "Three ADAR isoforms by cell type", y= "trancript counts") + theme(legend.position="bottom") + theme(axis.text=element_text(size=12),axis.title=element_text(size=18,face="bold"))
dev.off()

tiff("/media/sf_AIDD/Results/DESeq2/transcript/differential_expression/ADARB1line.tiff", units="in", width=10, height=10, res=900)
data1 <- read.csv("/media/sf_AIDD/Results/DESeq2/transcript/differential_expression/ADARB1.csv")
ggplot(data=data1, aes(x=index, y=counts, group=condition, shape=condition, colour=condition)) + geom_line(size=1.5) + geom_point(size=4) + scale_colour_manual(name="cell type"values=c("#FF6666", "#FFFF99", "#66FF66", "#6633FF", "#CC66FF"))+ labs(x = "ADARB1 isoforms by cell type", y= "trancript counts") + theme(legend.position="bottom") + theme(axis.text=element_text(size=12),axis.title=element_text(size=14,face="bold")) + scale_shape_manual(name="cell type", values=c(17,19,15,8,5))
dev.off()
