##these load all the programs used
library("DESeq2")
library("vsn")
library("dplyr")
library("ggplot2")
library("pheatmap")
library("RColorBrewer")
library("PoiClaClu")
library("ggbeeswarm")
library("genefilter")
library("sva")
table1 <- read.csv("gene_count_matrix.csv")
table2 <- read.csv("g_names.csv")
Data <- read.csv("PHENO_DATA.csv", row.names=1)
table3 <- merge(table2, table1, by="gene_id")
table4 <- table3$gene_id <- NULL
table5 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table3, "gene_count_matrixedited.csv", row.names=FALSE)
countData <- as.matrix(read.csv("gene_count_matrixedited.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
print("total rows in new matrix")
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
print("total number of rows with counts greater then 1")
nrow(dds)
tiff("rlogandvariance.tiff")
lambda <- 10^seq(from = -1, to = 2, length = 1000)
cts <- matrix(rpois(1000*100, lambda), ncol = 100)
meanSdPlot(cts, ranks = FALSE)
dev.off()
tiff("logtranscounts.tiff")
log.cts.one <- log2(cts + 1)
meanSdPlot(log.cts.one, ranks = FALSE)
dev.off()
print("Taking rlog of counts for downstream analysis")
rld <- rlog(dds, blind = FALSE)
print("Top three rows from new log matrix")
head(assay(rld), 3)
vsd <- vst(dds, blind = FALSE)
print("Further processing vst of new log matrix")
head(assay(vsd), 3)
dds <- estimateSizeFactors(dds)
df <- bind_rows(as_data_frame(log2(counts(dds, normalized=TRUE)[, 1:2]+1)) %>% mutate(transformation = "log2(x + 1)"), as_data_frame(assay(rld)[, 1:2]) %>% mutate(transformation = "rlog"), as_data_frame(assay(vsd)[, 1:2]) %>% mutate(transformation = "vst"))
colnames(df)[1:2] <- c("x", "y")
tiff("transcounts2sam.tiff")
ggplot(df, aes(x = x, y = y)) + geom_hex(bins = 80) + coord_fixed() + facet_grid( . ~ transformation)
dev.off()
sampleDists <- dist(t(assay(rld)))
sampleDists
sampleDistMatrix <- as.matrix( sampleDists )
rownames(sampleDistMatrix) <- paste( rld$condition)
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
poisd <- PoissonDistance(t(counts(dds)))
samplePoisDistMatrix <- as.matrix( poisd$dd )
rownames(samplePoisDistMatrix) <- paste( rld$condition)
colnames(samplePoisDistMatrix) <- NULL
tiff("PoisHeatmap.tiff")
pheatmap(samplePoisDistMatrix, clustering_distance_rows = poisd$dd, clustering_distance_cols = poisd$dd, col = colors)
dev.off()
tiff("PCAplot.tiff")
plotPCA(rld, intgroup = c("condition"))
dev.off()
pcaData <- plotPCA(rld, intgroup = c( "condition"), returnData = TRUE)
print("new pcaData matrix for creating PCAplots")
pcaData
percentVar <- round(100 * attr(pcaData, "percentVar"))
tiff("PCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mds <- as.data.frame(colData(rld))  %>% cbind(cmdscale(sampleDistMatrix))
tiff("MDSplot.tiff")
ggplot(mds, aes(x = `1`, y = `2`, color = condition)) + geom_point(size = 3) + coord_fixed()
dev.off()
mdsPois <- as.data.frame(colData(dds)) %>% cbind(cmdscale(samplePoisDistMatrix))
tiff("MDSpois.tiff")
ggplot(mdsPois, aes(x = `1`, y = `2`, color = condition)) + geom_point(size = 3) + coord_fixed()
dev.off()
print("Running DESeq2 command")
dds <- DESeq(dds)
res <- results(dds)
res <- results(dds, contrast=c("condition","A","B"))
mcols(res, use.names = TRUE)
print("summary of new results file")
summary(res)
res.05 <- results(dds, alpha = 0.05)
print("table of padj less then 0.05")
table(res.05$padj < 0.05)
resLFC1 <- results(dds, lfcThreshold=1)
print("table of log fold change greater then 1 with a padj of less then 0.1")
table(resLFC1$padj < 0.1) 
results <- results(dds, contrast = c("condition", "A", "B"))
write.csv(results, "resultsall.csv")
print("number of genes that are below pvalue 0.05")
sum(res$pvalue < 0.05, na.rm=TRUE)
print("number of genes that are below 0.05")
sum(!is.na(res$pvalue))
print("number of genes that have padj below 0.1")
sum(res$padj < 0.1, na.rm=TRUE)
resSig <- subset(res, padj < 0.1)
print("top genes based on the highest log2foldchange")
head(resSig[ order(resSig$log2FoldChange), ])
resSigdown <- resSig[ order(resSig$log2FoldChange), ]
write.csv(resSigdown, "Downreg.csv")
resSigup <- resSig[ order(resSig$log2FoldChange, decreasing = TRUE), ]
write.csv(resSigup, "Upreg.csv")
tiff("ADAR1counts.tiff")
plotCounts(dds, gene = "ADAR", intgroup=c("condition"))
dev.off()
geneCounts <- plotCounts(dds, gene = "ADAR", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR1counts2.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, shape = condition)) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_point(size = 3)
dev.off()
geneCounts <- plotCounts(dds, gene = "ADAR", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR1counts3.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
geneCounts <- plotCounts(dds, gene = "ADAR", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR1counts4.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_line() +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
tiff("ADAR2counts.tiff")
plotCounts(dds, gene = "ADARB1", intgroup=c("condition"))
dev.off()
geneCounts <- plotCounts(dds, gene = "ADARB1", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR2counts2.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, shape = condition)) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_point(size = 3)
dev.off()
geneCounts <- plotCounts(dds, gene = "ADARB1", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR2counts3.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_line() +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
geneCounts <- plotCounts(dds, gene = "ADARB1", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR2counts4.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
tiff("ADAR3counts.tiff")
plotCounts(dds, gene = "ADARB2", intgroup=c("condition"))
dev.off()
geneCounts <- plotCounts(dds, gene = "ADARB2", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR3counts2.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, shape = condition)) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_point(size = 3)
dev.off()
geneCounts <- plotCounts(dds, gene = "ADARB2", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR3counts3.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
geneCounts <- plotCounts(dds, gene = "ADARB2", intgroup = c("condition"), returnData = TRUE)
tiff("ADAR3counts4.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_line() +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
tiff("VEGFAcounts.tiff")
plotCounts(dds, gene = "VEGFA", intgroup=c("condition"))
dev.off()
geneCounts <- plotCounts(dds, gene = "VEGFA", intgroup = c("condition"), returnData = TRUE)
tiff("VEGFAcounts2.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition)) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_point(size = 3)
dev.off()
geneCounts <- plotCounts(dds, gene = "VEGFA", intgroup = c("condition"), returnData = TRUE)
tiff("VEGFAcounts3.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
geneCounts <- plotCounts(dds, gene = "VEGFA", intgroup = c("condition"), returnData = TRUE)
tiff("VEGFAcounts4.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_line() +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
tiff("VEGFBcounts.tiff")
plotCounts(dds, gene = "VEGFB", intgroup=c("condition"))
dev.off()
geneCounts <- plotCounts(dds, gene = "VEGFB", intgroup = c("condition"), returnData = TRUE)
tiff("VEGFBcounts2.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, shape = condition)) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_point(size = 3)
dev.off()
geneCounts <- plotCounts(dds, gene = "VEGFB", intgroup = c("condition"), returnData = TRUE)
tiff("VEGFBcounts3.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
geneCounts <- plotCounts(dds, gene = "VEGFB", intgroup = c("condition"), returnData = TRUE)
tiff("VEGFBcounts4.tiff")
ggplot(geneCounts, aes(x = condition, y = count, color = condition, label=rownames(pcaData))) + scale_y_log10() +  geom_beeswarm(cex = 3) + geom_line() +geom_text(aes(label=rownames(pcaData))) + geom_point(size = 0)
dev.off()
res <- lfcShrink(dds, contrast=c("condition","A","B"), res=res)
tiff("MAplot.tiff")
plotMA(res, ylim = c(-5, 5))
dev.off()
tiff("Histopvalue")
hist(res$pvalue[res$baseMean > 1], breaks = 0:20/20, col = "grey50", border = "white")
dev.off()
topVarGenes <- head(order(rowVars(assay(rld)), decreasing = TRUE), 60)
mat  <- assay(rld)[ topVarGenes, ]
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("top60heatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, fontsize_row=6)
dev.off()
##make gene counts file with correct names
table1 <- read.csv("gene_count_matrix.csv")
table2 <- read.csv("g_names.csv")
table3 <- merge(table2, table1, by="gene_id")
table4 <- table3$gene_id <- NULL
table5 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table3, "gene_count_matrixedited.csv", row.names=FALSE)
##make VEGFpathway way final table and heat map
table1 <- read.csv("gene_count_matrixedited.csv")
table2 <- read.csv("VEGFpathway_genes.csv")
table3 <- merge(table2, table1, by="gene_name")
table4 <- table3$t_id <- NULL
table5 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table3, "VEGFpathwayedited_counts.csv", row.names=FALSE)
tableB1 <- read.csv("resultsall.csv")
table5 <- colnames(tableB1)[c(1)] <- c("gene_name")
head(tableB1)
tableC3 <- merge(table3, tableB1, by="gene_name")
write.csv(tableC3, "resultsall_VEGFpathwayediting_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("VEGFpathwayedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("VEGFpathwayPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("VEGFpathwayheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##make PNS developmental genes final table and heat map
table12 <- read.csv("gene_count_matrixedited.csv")
table22 <- read.csv("pns_deve_genes.csv")
table32 <- merge(table22, table12, by="gene_name")
table42 <- table32$t_id <- NULL
table52 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table32, "pns_deve_genesedited_counts.csv", row.names=FALSE)
tableC32 <- merge(table32, tableB1, by="gene_name")
write.csv(tableC32, "resultsall_pns_deveediting_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("pns_deve_genesedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("pns_deve_genesPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("pns_deve_genesheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##make neurological genes final table and heat map
table13 <- read.csv("gene_count_matrixedited.csv")
table23 <- read.csv("neuro_genes.csv")
table33 <- merge(table23, table13, by="gene_name")
table43 <- table33$t_id <- NULL
table53 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table33, "neuro_genesedited_counts.csv", row.names=FALSE)
tableC33 <- merge(table33, tableB1, by="gene_name")
write.csv(tableC33, "resultsall_neuro_editing_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("neuro_genesedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("neuro_genesPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("neuro_genesheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##make neurological developmental genes final table and heat map
table14 <- read.csv("gene_count_matrixedited.csv")
table24 <- read.csv("neuro_deve_genes.csv")
table34 <- merge(table24, table14, by="gene_name")
table44 <- table34$t_id <- NULL
table54 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table34, "neuro_deve_genesedited_counts.csv", row.names=FALSE)
tableC34 <- merge(table34, tableB1, by="gene_name")
write.csv(tableC34, "resultsall_neuro_deveediting_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("neuro_deve_genesedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("neuro_deve_genesPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("neuro_deve_genesheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##make CNS developmental genes final table and heat map
table15 <- read.csv("gene_count_matrixedited.csv")
table25 <- read.csv("cns_deve_genes.csv")
table35 <- merge(table25, table15, by="gene_name")
table45 <- table35$t_id <- NULL
table55 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table35, "cns_deve_genesedited_counts.csv", row.names=FALSE)
tableC35 <- merge(table35, tableB1, by="gene_name")
write.csv(tableC35, "resultsall_cns_deve_genesediting_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("cns_deve_genesedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("cns_deve_genesPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("cns_deve_genesheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##make brain developmental genes final table and heat map
table16 <- read.csv("gene_count_matrixedited.csv")
table26 <- read.csv("brain_deve_genes.csv")
table36 <- merge(table26, table16, by="gene_name")
table46 <- table36$t_id <- NULL
table56 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table36, "brain_deve_genesedited_counts.csv", row.names=FALSE)
tableC36 <- merge(table36, tableB1, by="gene_name")
write.csv(tableC36, "resultsall_brain_deveediting_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("brain_deve_genesedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("brain_deve_genesPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("brain_deve_genesheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##make positive regulation of myeloid differentiation genes final table and heat map
table16 <- read.csv("gene_count_matrixedited.csv")
table26 <- read.csv("pos_myeloid_diff_genes.csv")
table36 <- merge(table26, table16, by="gene_name")
table46 <- table36$t_id <- NULL
table56 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table36, "pos_myeloid_diff_genesedited_counts.csv", row.names=FALSE)
tableC36 <- merge(table36, tableB1, by="gene_name")
write.csv(tableC36, "resultsall_pos_myeloid_diffediting_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("pos_myeloid_diff_genesedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("pos_myeloid_diff_genesPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("pos_myeloid_diff_genesheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##make brain developmental genes final table and heat map
table16 <- read.csv("gene_count_matrixedited.csv")
table26 <- read.csv("neg_myeloid_diff_genes.csv")
table36 <- merge(table26, table16, by="gene_name")
table46 <- table36$t_id <- NULL
table56 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table36, "neg_myeloid_diff_genesedited_counts.csv", row.names=FALSE)
tableC36 <- merge(table36, tableB1, by="gene_name")
write.csv(tableC36, "resultsall_neg_myeloid_diffediting_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("neg_myeloid_diff_genesedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("neg_myeloid_diff_genesPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("neg_myeloid_diff_genesheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##make brain developmental genes final table and heat map
table16 <- read.csv("gene_count_matrixedited.csv")
table26 <- read.csv("myeloid_homo_genes.csv")
table36 <- merge(table26, table16, by="gene_name")
table46 <- table36$t_id <- NULL
table56 <- colnames(table3)[c(2:17)] <- rownames(Data)[c(1:16)]
write.csv(table36, "myeloid_homo_genesedited_counts.csv", row.names=FALSE)
tableC36 <- merge(table36, tableB1, by="gene_name")
write.csv(tableC36, "resultsall_myeloid_homoediting_counts.csv", row.names=FALSE)
countData <- as.matrix(read.csv("myeloid_homo_genesedited_counts.csv", row.names="gene_name"))
colData <- read.csv("PHENO_DATA.csv", row.names=1)
print("do all your row names and colnames match with the PHENO_DATA file")
all(rownames(colData) %in% colnames(countData))
countData <- countData[, rownames(colData)]
print("after renaming columns with PHENO_DATA file do they still match")
all(rownames(colData) == colnames(countData))
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ condition)
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)
rld <- rlog(dds, blind = FALSE)
tiff("myeloid_homo_genesPCAplot2.tiff")
ggplot(pcaData, aes(x = PC1, y = PC2, color = condition, group = condition, label=rownames(pcaData))) + geom_point(size = 0) + xlab(paste0("PC1: ", percentVar[1], "% variance")) + ylab(paste0("PC2: ", percentVar[2], "% variance")) + coord_fixed() +geom_text(aes(label=rownames(pcaData)))
dev.off()
mat  <- assay(rld)
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld)[, c("condition")])
rownames(anno) <- colData[,3]
colnames(anno) <- "gene_name"
tiff("myeloid_homo_genesheatmap.tiff")
pheatmap(mat, annotation_col = anno, annotation_legend=FALSE, show_rownames = FALSE)
dev.off()
##VEGF final count tables
table1 <- read.csv("gene_count_matrixedited.csv")
table2 <- read.csv("VEGFgene.csv")
table3 <- merge(table2, table1, by="gene_name")
tableB12 <- read.csv("resultsall.csv")
table5 <- colnames(tableB12)[c(1)] <- c("gene_name")
head(tableB12)
tableC6 <- merge(table3, tableB12, by="gene_name")
write.csv(tableC6, "resultsVEGF_gene_counts.csv", row.names=FALSE)
tablebargraph <- t(tableC6)
colnames(tablebargraph) <- tableC6[,1]
tablebargraph2 <- tablebargraph[-c(1, 18, 19, 20, 21, 22, 23), ]
write.csv(tablebargraph2, "tablebargraph2.csv")
tablebargraph2 <- read.csv("tablebargraph2.csv")
tablebargraphY <- colnames(tablebargraph2)[1] <- "sample"
tablebargraph2
Data <- read.csv("bargraphindex.csv")
tablebargraph3 <- merge(Data, tablebargraph2, by="sample")
tablebargraph4 <- aggregate(tablebargraph3[, 3:5], list(tablebargraph3$gene_name), mean)
tablebargraph5 <- t(tablebargraph4)
tablebargraph5 <- tablebargraph5[-c(1),]
write.csv(tablebargraph5, "5.csv")
write.csv(tablebargraph5, "6.csv")
tablebargraph5 <- read.csv("5.csv")
colnames(tablebargraph5)[1] <- "gene_name"
tablebargraphG <- tablebargraph5$V2 <- NULL
colnames(tablebargraph5)[2] <- "counts"
tablebargraph6 <- read.csv("6.csv")
colnames(tablebargraph6)[1] <- "gene_name"
tablebargraphH <- tablebargraph6$V1 <- NULL
colnames(tablebargraph6)[2] <- "counts"
tablebargraph5["condition"] <- "AML"
tablebargraph6["condition"] <- "Normal"
final <- rbind(tablebargraph5, tablebargraph6)
tiff("VEGFbargraph.tiff")
ggplot(final, aes(x=gene_name, y=counts, fill=condition)) +
    geom_bar(stat="identity", position=position_dodge(), colour="black")
dev.off()
##ADAR final count table
table1 <- read.csv("gene_count_matrixedited.csv")
table2 <- read.csv("ADARgene.csv")
Data <- read.csv("bargraphindex.csv")
table3 <- merge(table2, table1, by="gene_name")
table4 <- table3$gene_id <- NULL
tableC3 <- merge(table3, tableB12, by="gene_name")
write.csv(tableC3, "resultsADAR_gene_counts.csv", row.names=FALSE)
tablebargraph <- t(tableC3)
colnames(tablebargraph) <- tableC3[,1]
tablebargraph2 <- tablebargraph[-c(1, 18, 19, 20, 21, 22, 23), ]
write.csv(tablebargraph2, "tablebargraph2.csv")
tablebargraph2 <- read.csv("tablebargraph2.csv")
tablebargraphY <- colnames(tablebargraph2)[1] <- "sample"
tablebargraph2
Data <- read.csv("bargraphindex.csv")
tablebargraph3 <- merge(Data, tablebargraph2, by="sample")
tablebargraph4 <- aggregate(tablebargraph3[, 3:5], list(tablebargraph3$gene_name), mean)
tablebargraph5 <- t(tablebargraph4)
tablebargraph5 <- tablebargraph5[-c(1),]
write.csv(tablebargraph5, "5.csv")
write.csv(tablebargraph5, "6.csv")
tablebargraph5 <- read.csv("5.csv")
colnames(tablebargraph5)[1] <- "gene_name"
tablebargraphG <- tablebargraph5$V2 <- NULL
colnames(tablebargraph5)[2] <- "counts"
tablebargraph6 <- read.csv("6.csv")
tablebargraphE <- colnames(tablebargraph6)[1] <- "gene_name"
tablebargraphH <- tablebargraph6$V1 <- NULL
tablebargraphI <- colnames(tablebargraph6)[2] <- "counts"
tablebargraph5["condition"] <- "AML"
tablebargraph6["condition"] <- "Normal"
final <- rbind(tablebargraph5, tablebargraph6)
tiff("ADARbargraph.tiff")
ggplot(final, aes(x=gene_name, y=counts, fill=condition)) +
    geom_bar(stat="identity", position=position_dodge(), colour="black")
dev.off()
tableAA <- rbind(tableC3, tableC6)
write.csv(tableAA, "ADAR_VEGF_final.csv", row.names=FALSE)
sessionInfo()

