##need to make celltranslist and cellgenelist from upreg downreg upreg_tran and downreg_gene.csv files.  Make one for each 
library("gdata")
##have to create UpReg.csv and DownReg.csv and top100.csv need to have gene_names in two columns condition_1, condition_2
geneLists <- read.csv("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/UpReg.csv")
head(geneLists)
tail(geneLists)
geneLS <- lapply(as.list(geneLists), function(x) x[x != ""])
lapply(geneLS, tail)
names(geneLS) <- c("condition_1", "condition_2")
require("VennDiagram")
VENN.LIST <- geneLS
jpeg("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/UpReg.jpeg")
venn.plot <- venn.diagram(VENN.LIST, NULL, category.names=c("condition_1", "condition_2"), fill=c("lightgreen", "yellow"), alpha=c(0.5,0.5), cex = 2, cat.fontface=4)
grid.draw(venn.plot)
dev.off()
require("gplots")
a <- venn(VENN.LIST, show.plot=TRUE)
str(a)
inters <- attr(a,"intersections")
lapply(inters, head)
sink("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/UpReg.txt")
inters
sink()
geneLists <- read.csv("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/DownReg.csv")
head(geneLists)
tail(geneLists)
geneLS <- lapply(as.list(geneLists), function(x) x[x != ""])
lapply(geneLS, tail)
names(geneLS) <- c("condition_1", "condition_2")
require("VennDiagram")
VENN.LIST <- geneLS
jpeg("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/DownReg.jpeg")
venn.plot <- venn.diagram(VENN.LIST, NULL, category.names=c("condition_1", "condition_2"), fill=c("lightgreen", "yellow"), alpha=c(0.5,0.5), cex = 2, cat.fontface=4)
grid.draw(venn.plot)
dev.off()
require("gplots")
a <- venn(VENN.LIST, show.plot=TRUE)
str(a)
inters <- attr(a,"intersections")
lapply(inters, head)
sink("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/DownReg.txt")
inters
sink()
geneLists <- read.csv("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/top100.csv")
head(geneLists)
tail(geneLists)
geneLS <- lapply(as.list(geneLists), function(x) x[x != ""])
lapply(geneLS, tail)
names(geneLS) <- c("condition_1", "condition_2")
require("VennDiagram")
VENN.LIST <- geneLS
jpeg("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/top100.jpeg")
venn.plot <- venn.diagram(VENN.LIST, NULL, category.names=c("condition_1", "condition_2"), fill=c("lightgreen", "yellow"), alpha=c(0.5,0.5), cex = 2, cat.fontface=4)
grid.draw(venn.plot)
dev.off()
require("gplots")
a <- venn(VENN.LIST, show.plot=TRUE)
str(a)
inters <- attr(a,"intersections")
lapply(inters, head)
sink("/media/sf_AIDD/Results/DESeq2/gene/differential_expression/top100.txt")
inters
sink()
