library("VennDiagram")
library("gdata")
library("gplots")
Lists <- read.csv("/media/sf_AIDD/Results/variant_calling/haplotype/transcript/moderate_impact/transcriptlistvenn.csv")
head(Lists)
tail(Lists)
LS <- lapply(as.list(Lists), function(x) x[x != ""])
lapply(LS, tail)
names(LS) <- c("hESC", "Endo", "Meso", "NPC", "PNCC")
VENN.LIST <- LS
tiff("/media/sf_AIDD/Results/variant_calling/haplotype/transcript/moderate_impact/transcriptlistvenn.tiff", units="in", width=10, height=10, res=900)
venn.plot <- venn.diagram(VENN.LIST, NULL, category.names=c("hESC", "Endo", "Meso", "NPC", "PNCC"), fill=c("#FF6666", "#FFFF99", "#66FF66", "#6633FF", "#CC66FF"), alpha=c(0.5,0.5,0.5,0.5,0.5), cex = 2, cat.fontface=4)
grid.draw(venn.plot)
dev.off()
a <- venn(VENN.LIST, show.plot=TRUE)
str(a)
inters <- attr(a,"intersections")
lapply(inters, head)
sink("/media/sf_AIDD/Results/variant_calling/haplotype/transcript/moderate_impact/transciptlistVennDiagrams.txt")
inters
sink()
