##first need to merge two condition HIGH and two condition Moderate to create two Venn diagrams
##create venn diagram comparing HIGH Normal to HIGH AML
geneLists <- read.csv("/media/sf_AIDD/Results/variant_calling/haplotype/gene/high_impact/HIGH.csv")
head(geneLists)
tail(geneLists)
geneLS <- lapply(as.list(geneLists), function(x) x[x != ""])
lapply(geneLS, tail)
names(geneLS) <- c("condition_1", "condition_2")
require("VennDiagram")
VENN.LIST <- geneLS
jpeg("/media/sf_AIDD/Results/variant_calling/haplotype/gene/high_impact/HIGH.jpeg")
venn.plot <- venn.diagram(VENN.LIST, NULL, category.names=c("condition_1", "condition_2"), fill=c("lightgreen", "yellow"), alpha=c(0.5,0.5), cex = 2, cat.fontface=4, main="High impact RNAediting sites in Normal verse AML")
grid.draw(venn.plot)
dev.off()
require("gplots")
a <- venn(VENN.LIST, show.plot=TRUE)
str(a)
inters <- attr(a,"intersections")
lapply(inters, head)
sink("/media/sf_AIDD/Results/variant_calling/haplotype/gene/high_impact/HIGH.txt")
inters
sink()
geneLists <- read.csv("/media/sf_AIDD/Results/variant_calling/haplotype/gene/moderate_impact/Moderate.csv")
head(geneLists)
tail(geneLists)
geneLS <- lapply(as.list(geneLists), function(x) x[x != ""])
lapply(geneLS, tail)
names(geneLS) <- c("condition_1", "condition_2")
require("VennDiagram")
VENN.LIST <- geneLS
jpeg("/media/sf_AIDD/Results/variant_calling/haplotype/gene/moderate_impact/Moderate.jpeg")
venn.plot <- venn.diagram(VENN.LIST, NULL, category.names=c("condition_1", "condition_2"), fill=c("lightgreen", "yellow"), alpha=c(0.5,0.5), cex = 2, cat.fontface=4, main="High impact RNAediting sites in Normal verse AML")
grid.draw(venn.plot)
dev.off()
require("gplots")
a <- venn(VENN.LIST, show.plot=TRUE)
str(a)
inters <- attr(a,"intersections")
lapply(inters, head)
sink("/media/sf_AIDD/Results/variant_calling/haplotype/gene/moderate_impact/Moderate.txt")
inters
sink()
